name: Directory Build (Python)

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Run script
        run: python build.py
      - name: Move directory.json to root
        run: |
          if [ -f directory.json ]; then
            mv directory.json ./directory.json
          fi
        
